name: "terraform apply"
description: "terraform apply"
inputs:
  working_directory:
    description: "working_directory"
    required: true
  terraform_parallelism:
    description: "terraform_parallelism"
    required: true
  terraform_lock_timeout:
    description: "terraform_lock_timeout"
    required: true
  project_id:
    description: "project_id"
    required: true
  GCP_CREDENTIALS:
    description: "gcp credential"
    required: true
  GITHUB_TOKEN:
    description: "github token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Detect Terraform Version
      run: printf "terraform_version=%s" $(cat .terraform-version) >> $GITHUB_ENV
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.terraform_version }}
    - name: Authanticate to Google Cloud Platform
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ inputs.project_id }}
        credentials_json: ${{ inputs.GCP_CREDENTIALS }}
    - name: Terraform Init
      run: terraform init
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - name: Terraform Apply
      id: apply
      run: terraform apply -input=false -parallelism=${{ inputs.terraform_parallelism }} -lock-timeout=${{ inputs.terraform_lock_timeout }} -auto-approve
      working-directory: ${{ inputs.working_directory }}
      shell: bash
